server:
  port: 8779
spring:
  freemarker:
    suffix: .html
    cache: false
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      #单个文件最大限制
      max-file-size: 2MB
      #上传文件加起来的最大限制
      max-request-size: 20MB
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


